# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed


# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
#--------------------------

title: Yo0oN                          # the main title

tagline: Yo0oN's blog.  # it will display as the sub-title

<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
description: >-                        # used by seo meta and the atom feed
<<<<<<< HEAD
  Yo0oN's blog.
=======
description: Hi                        # used by seo meta and the atom feed
>>>>>>> 7664893... Update _config.yml
=======
description: Yo0oN's blog                        # used by seo meta and the atom feed
>>>>>>> b592793... Update _config.yml
=======
description: >-                        # used by seo meta and the atom feed
  Yo0oN's blog.
>>>>>>> 269518d... Update _config.yml
=======
  Hi
>>>>>>> add98f2... 깃허브 블로그 생성
=======
description: Hi                        # used by seo meta and the atom feed
>>>>>>> fb62a5c... Update _config.yml
=======
description: Yo0oN's blog                        # used by seo meta and the atom feed
>>>>>>> 1ee4f48... Update _config.yml

# Replace with the website url, e.g. 'https://username.github.io'
url: 'https://yo0on.github.io'

author: Choi Yoon-Jeong                  # change to your full name

avatar: /assets/img/avatar.jpg   # support internet resources 프로필 사진 경로

github:
  username: Yo0oN             # change to your github username

notion:
  username: chl4855            # change to your twitter username

#twitter:
  #username: twitter_username            # change to your twitter username

social:
  name: Choi Yoon-Jeong                  # it will shows as the copyright owner in Footer
  email: 4855chl@gmail.com             # change to your email address
  links:
    # The first element serves as the copyright owner's link
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
    - https://www.notion.so/4codingtest/604176ef27ee40ecb8b1872582f4fa34
>>>>>>> 7664893... Update _config.yml
=======
>>>>>>> b592793... Update _config.yml
    - https://github.com/Yo0oN       # change to your github homepage
    - https://www.notion.so/4codingtest/604176ef27ee40ecb8b1872582f4fa34
    # Uncomment below to add more social links
=======
    #- https://twitter.com/username      # change to your twitter homepage
    - https://github.com/Yo0oN       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.notion.so/4codingtest/604176ef27ee40ecb8b1872582f4fa34
>>>>>>> add98f2... 깃허브 블로그 생성
=======
    - https://www.notion.so/4codingtest/604176ef27ee40ecb8b1872582f4fa34
=======
>>>>>>> 1ee4f48... Update _config.yml
    - https://github.com/Yo0oN       # change to your github homepage
    - https://www.notion.so/4codingtest/604176ef27ee40ecb8b1872582f4fa34
    # Uncomment below to add more social links
>>>>>>> fb62a5c... Update _config.yml
    # - https://www.linkedin.com/in/username

#google_site_verification: google_meta_tag_verification # change to your verification string

#--------------------------


# Only if your site type is GitHub Project sites and doesn't have a custom domain,
# change below value to '/projectname'.
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
# 깃허브 블로그로 사용중이니 빈칸으로 둔다. 만약 프로젝트 이름을 적는다면 이름/github.io/프로젝트 로 도메인이 바뀐다.
baseurl: ''
=======
baseurl: '/Yo0oN.githum.io'
>>>>>>> 7664893... Update _config.yml
=======
=======
# 깃허브 블로그로 사용중이니 빈칸으로 둔다. 만약 프로젝트 이름을 적는다면 이름/github.io/프로젝트 로 도메인이 바뀐다.
>>>>>>> 650c294... Update _config.yml
baseurl: ''
>>>>>>> bf8d8bd... Update _config.yml
=======
baseurl: '/Yo0oN.githum.io'
>>>>>>> fb62a5c... Update _config.yml
=======
=======
# 깃허브 블로그로 사용중이니 빈칸으로 둔다. 만약 프로젝트 이름을 적는다면 이름/github.io/프로젝트 로 도메인이 바뀐다.
>>>>>>> 37bc089... Update _config.yml
baseurl: ''
>>>>>>> 5eb4e08... Update _config.yml

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Seoul

#google_analytics:
  #id: ''          # Fill with your Google Analytics ID
  #pv:
    # The Google Analytics pageviews switch.
    # DO NOT enable it unless you know how to deploy the Google Analytics superProxy.
    #enabled: false
    # the next options only valid when `google_analytics.pv` is enabled.
    #proxy_url: ''
    #proxy_endpoint: ''
    #cache: false  # pv data local cache, good for the users from GFW area.

#disqus:
  #comments: false  # boolean type, the global switch for posts comments.
  #shortname: ''    # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname


# Prefer color scheme setting, available values:
#
#     dual   - Follow the system prefer color by default, and a toggle will display
#              in the left bottom of Sidebar, which used for switch the theme between dark and light.
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: dual

# boolean type, global switch for ToC in posts.
toc: true

paginate: 5 # 메인에서 보여주는 페이지 수

markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# DO NOT change this unless you're a Pro user on Jekyll and Web development,
# or you think you're smart enough to change other relevant URLs within this template.
permalink: /posts/:title/

defaults:
  -
    scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      location: Post
      breadcrumb:
        -
          label: Posts
          url: /
  -
    scope:
      path: _drafts
    values:
      comments: false
  -
    scope:
      path: tags
    values:
      tab_active: Tags
      location: Tag
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Tags
          url: /tabs/tags/
  -
    scope:
      path: categories
    values:
      tab_active: Categories
      location: Category
      breadcrumb:
        -
          label: Home
          url: /
        -
          label: Categories
          url: /tabs/categories/
  -
    scope:
      path: tabs
    values:
      layout: page
      dynamic_title: true    # Hide title in mobile screens.
      breadcrumb:
        -
          label: Home
          url: /


sass:
  sass_dir: /assets/css
  style: compressed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: [html, head, body, dt, dd, rt, rp,
            optgroup, option, colgroup, caption,
            thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

exclude:
  - vendor        # Avoid Jekyll mistakenly read the vendor directory on Travis-CI's VM .
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE

sitemap_exclude:  # Sitemap will exclude the following items.
  fuzzy:
    - /assets/
    - /images/
  accurate:
    - /norobots/
    - /tabs/
    - /categories/
    - /tags/
    - /posts/
    - 404.html
    - feed.xml
    - sitemap.xml
    - robots.txt
    - redirects.json
